### ISSUE TITLE
Role request: PyLoad

### ISSUE THREAD

**Issue by kaizensh** [saltyorg/Sandbox#1]
pyLoad is a free and open source download manager written in Python and designed to be extremely lightweight, easily extensible and fully manageable via web. All common video-sites, one-click-hosters, container formats and well known web standards are supported to allow you to download your files. Additionaly, pyLoad has a great variety of plugins to automate common tasks and make unattended running possible.

I see there is a role listed in Cloudbox community repo for a solution but I'm not sure how up to date/supported it is, may be a start for reference
- https://github.com/Cloudbox/Community/blob/master/roles/pyload/tasks/main.yml

Other links:
- https://hub.docker.com/r/linuxserver/pyload
- https://pyload.net/

**Comment by maximuskowalski** [comment]
Thank you for the links - it makes things a lot easier to quickly checkout.

Once salty wakes up I will talk to him about sandbox and try to start adding some roles in the next few days.
