### ISSUE TITLE
Role Request: Cloudflare DDNS

### ISSUE THREAD

**Issue by inzi2u** [saltyorg/Sandbox#10]
There is a lot of interest  in using SB for a local setup. On my venture to get it one done.
i required a Cloudflare DDNS updater. 
and came across this Docker, that was pretty useful.
Coupled with the youtube video, it was pretty helpful to set things up.

Docker : https://hub.docker.com/r/oznu/cloudflare-ddns
Youtube : https://www.youtube.com/watch?v=Nf7m3h11y-s&t=282s

**Comment by saltydk** [comment]
I assume this is already covered in the ddclient role.

**Comment by inzi2u** [comment]
@saltydk i have not tried out ddclient, but Cloudflare DDNS did work great. although you have to sorta convert the A records that SB makes in to CNAME records and proxify them. That helped me get around the Hairpin NAT. Nothing else worked.
And i didnt have to turn the rpi in to a DHCP server.

**Comment by saltydk** [comment]
CNAMEs are a no go as that breaks Saltbox' ability to update them when you run tags.

**Comment by maximuskowalski** [comment]
Have you looked at the ddclient role at all yet @inzi2u ? Is there any need for Cloudflare DDNS still?

**Comment by maximuskowalski** [comment]
Still testing or happy to close this?
