### ISSUE TITLE
App Request: ganymede

### ISSUE THREAD

**Issue by maximuskowalski** [saltyorg/Sandbox#101]
Twitch VOD and Stream archiving platform with a rendered chat. 
Files are saved in a friendly format allowing for use without Ganymede.

https://github.com/Zibbp/ganymede

## About
Ganymede allows archiving of past streams (VODs) and livestreams both with a rendered chat. All files are saved in a friendly way that doesn't require Ganymede to view them (see [file structure](https://github.com/Zibbp/ganymede/wiki/File-Structure)).

## Features
Light/dark mode toggle.
Twitch VOD/Livestream support.
Queue holds.
Queue task restarts.
Full VOD, Channel, and User management.
Custom post-download video FFmpeg parameters.
Custom chat render parameters.
Webhook notifications.

https://github.com/Zibbp/ganymede/blob/master/docker-compose.yml

**Comment by maximuskowalski** [comment]
I'm unsure if this belongs in Sandbox or Sandpit - it's archiving video and VOD but still seems potentially outside the role of a media server.

**Comment by bonny1992** [comment]
+1 from me.
Imho it's on the same level as Tubearchivist, and we have that in Sandbox.

**Comment by owine** [comment]
After a poll in Discord, this role is not planned. Feel free to submit a PR if the role is desired.
