### ISSUE TITLE
Role request: qBit Manage

### ISSUE THREAD

**Issue by kaizensh** [saltyorg/Sandbox#11]
This is a program used to manage your qBittorrent instance such as:
- Tag torrents based on tracker URL and set seed goals/limit upload speed by tag (only tag torrents that have no tags)
- Update categories based on save directory
- Remove unregistered torrents (delete data & torrent if it is not being cross-seeded, otherwise it will just remove the torrent)
- Automatically add cross-seed torrents in paused state. *Note: cross-seed now allows for torrent injections directly to qBit, making this feature obsolete.*
- Recheck paused torrents sorted by lowest size and resume if completed
- Remove orphaned files from your root directory that are not referenced by qBittorrent
- Tag any torrents that have no hard links and allows optional cleanup to delete these torrents and contents based on maximum ratio and/or time seeded
- RecycleBin function to move files into a RecycleBin folder instead of deleting the data directly when deleting a torrent
- Built-in scheduler to run the script every x minutes. (Can use --run command to run without the scheduler)

Links
- https://github.com/StuffAnThings/qbit_manage/wiki/Docker-Installation
- https://hub.docker.com/r/bobokun/qbit_manage
- https://github.com/StuffAnThings/qbit_manage

**Comment by maximuskowalski** [comment]
I will try to take a look at this over the weekend and maybe talk to @Visorask about the setup.

**Comment by maximuskowalski** [comment]
https://hotio.dev/containers/qbitmanage/

Now also available.

**Comment by maximuskowalski** [comment]
Merged in #19 - leaving open as reminder because docs are needed.
