### ISSUE TITLE
App Request: Photoprism

### ISSUE THREAD

**Issue by RaneyDazed** [saltyorg/Sandbox#123]
## [Photoprism](https://github.com/photoprism/photoprism) 
PhotoPrism® is an AI-Powered Photos App for the [Decentralized Web](https://en.wikipedia.org/wiki/Decentralized_web). It makes use of the latest technologies to tag and find pictures automatically without getting in your way. You can run it at home, on a private server, or in the cloud.

Here is the [Documentation](https://docs.photoprism.app/getting-started/)

**Comment by maximuskowalski** [comment]
Just a note to anyone looking at this, Raneydazed is currently working on a role.

**Comment by owine** [comment]
Completed by @RaneyDazed in #132
