### ISSUE TITLE
Change Stash Image

### ISSUE THREAD

**Issue by teka6** [saltyorg/Sandbox#125]
Change image of the stash container to the one from [Hotio](https://github.com/hotio/stash)

Reason for that:
for stash there are a lot of plugins and scripts which are useful. These in turn rely on python packages.
To avoid adding them manually after each upgrade an automated script variant would be helpful.

**Comment by owine** [comment]
This isn't quite a drop in replacement due to path differences but I will see if I can adapt this to be backwards compatible.
