### ISSUE TITLE
wireguard server

### ISSUE THREAD

**Issue by arslanakhter** [saltyorg/Sandbox#126]
Please add wireguard implementation. where we can connect to our server through vpn and download content while being on same network.

**Comment by owine** [comment]
https://github.com/saltyorg/Sandbox/commit/f34e6dc2cfab63f14b8d8b545c9c5a2eed7721ec

https://github.com/saltyorg/docs/commit/6bbb1f428b63883df0e82c2d1b41bedc1f457a0b
