### ISSUE TITLE
App Request: Tube Archivist 

### ISSUE THREAD

**Issue by DrMxrcy** [saltyorg/Sandbox#131]
https://github.com/tubearchivist/tubearchivist

https://github.com/tubearchivist/tubearchivist/blob/master/docker-compose.yml

https://www.tubearchivist.com/

**Comment by maximuskowalski** [comment]
### Your self hosted YouTube media server

## Core functionality
* Subscribe to your favorite YouTube channels
* Download Videos using **yt-dlp**
* Index and make videos searchable
* Play videos
* Keep track of viewed and unviewed videos
