### ISSUE TITLE
add scripts to stash container

### ISSUE THREAD

**Issue by teka6** [saltyorg/Sandbox#136]
For Stash to work with scripts and plugins you have to install some python packages within the container.
so for that we need a script with following post-process installations:

pip install stashapp-tools
pip install pystashlib
pip install pyvis
pip install requests
pip install psutil
pip install Unidecode
pip install cloudscraper
pip install lxml
pip install beautifulsoup4

**Comment by owine** [comment]
I don't see a particular reason to ship this by default. You can write your own cont-init script and use the inventory system to mount the script in to run on container start.
