### ISSUE TITLE
n8n apprequest

### ISSUE THREAD

**Issue by maximuskowalski** [saltyorg/Sandbox#142]
kaizen — Today at 08:46
how hard would this be to add as a role? https://n8n.io/

> The workflow automation platform that doesn't box you in, that you never outgrow

https://n8n.io/
https://github.com/n8n-io/n8n
https://n8n.io/get-started/
https://docs.n8n.io/hosting/installation/docker/

**Comment by JigSawFr** [comment]
WIP

**Comment by JigSawFr** [comment]
Almost ready, just need to prettify and commit :)

**Comment by JigSawFr** [comment]
Submitted: https://github.com/saltyorg/Sandbox/pull/146
