### ISSUE TITLE
Role request: OpenLiteSpeed WordPress

### ISSUE THREAD

**Issue by kaizensh** [saltyorg/Sandbox#151]
While I know we already have a Wordpress role available, I think it would be great to offer an OpenLiteSpeed version also as there is quite drastic performance boosts compared to the original and loads of new features/customization.

Links:
- https://hub.docker.com/r/litespeedtech/openlitespeed
- https://openlitespeed.org/

**Comment by maximuskowalski** [comment]
@kaizensh did you end up creating a compose file for this, or have any extra info you wish to share?

**Comment by owine** [comment]
After a poll in Discord, this role is not planned. Feel free to submit a PR if the role is desired.
