### ISSUE TITLE
Role Request: nabarr

### ISSUE THREAD

**Issue by davehkb** [saltyorg/Sandbox#17]
I would like to add nabarr to saltybox.

Docker:
https://github.com/l3uddz/nabarr#docker

**Comment by maximuskowalski** [comment]
Now added but documentation still to do.

Install with 
`sb install sandbox-nabarr`

The example config from l3uddz will be created, you need to copy this and edit it to suit your own setup. I've edited the sonarr and radarr address which should work fine - follow that example and use your arrX names if needed.
`cp "/opt/nabarr/config.yml.sample" "/opt/nabarr/config.yml"`

Watch the log to catch any errors in your setup.
`tail -f "/opt/nabarr/activity.log"`

Let me know if its working for you and I'll create some minimal docs.

**Comment by maximuskowalski** [comment]
minimal docs made, closing.
