### ISSUE TITLE
App Request: mkdocs

### ISSUE THREAD

**Issue by YozoraXCII** [saltyorg/Sandbox#170]
Would it be possible to add mkdocs as an app that can be installed?

mkdocs-material as an available theme too would be ideal.

https://www.mkdocs.org/
https://hub.docker.com/r/squidfunk/mkdocs-material/

EDIT: Whilst I appreciate that the installation of mkdocs is straight forward, there are aspects (like the domain name, the folder heirarchy, and the ease of integration into things like portainer [assuming the docker image was used], updatability) that SB handles very nicely and ties up neatly that would perhaps be a bit more difficult to reproduce locally.

**Comment by saltydk** [comment]
The only reason you'd want mkdocs installed one a system is to use it as a developer environment in my opinion as with most other static site generators you usually host them on Github Pages or Cloudflare Pages. Unless a use case outside of that is explained I suggest that @owine and @maximuskowalski close this.
