### ISSUE TITLE
[App request] listrr.pro Sonarr Bridge 

### ISSUE THREAD

**Issue by FevLoad** [saltyorg/Sandbox#176]
I would like to see 
https://github.com/TheUltimateC0der/listrr.pro.Sonarr
added to app installer on saltbox 
this script is a fix for  tracktarr problem known of unable to connect to sonarr 
this script uses listrr to do the job directly using user's profile at listrr site

**Comment by maximuskowalski** [comment]
Did @TheUltimateC0der end up setting something up for this already?

**Comment by owine** [comment]
After a poll in Discord, this role is not planned. Feel free to submit a PR if the role is desired.
