### ISSUE TITLE
Role Request: Doplarr

### ISSUE THREAD

**Issue by thatsnasty** [saltyorg/Sandbox#18]
Requestrr development has ceased, and has been archived. Whilst it should work fine for the foreseeable future I thought it might be an idea to test [Doplarr ](https://github.com/kiranshila/Doplarr).

I would have a crack miyself at the role but because it is my first one and the time of year, I thought I'd post it here first if someone else wanted it sooner. Otherwise I will re-visit in the new year.

**Comment by kaizensh** [comment]
+1 to this request. I just started to set up my request apps and noticed that requesterr has been archived and would like an active project to use in combination with overseerr.

**Comment by maximuskowalski** [comment]
Any progress on creating this role?

**Comment by thatsnasty** [comment]
Sorry Max, I posted in the discord asking someone else to take over I should have also posted it here.

**Comment by maximuskowalski** [comment]
Yes, I remember. I think @kaizensh above had plans to work on this.

**Comment by grostim** [comment]
Hi!
If nobody has started working on this one, i can try.

**Comment by maximuskowalski** [comment]
I think you are safe :)

Add a link to the docker image you use in the pull request, and maybe any testing you did. We should probably migrate the community pull request template over.

**Comment by maximuskowalski** [comment]
Doplarr merged in PR #41

**Comment by maximuskowalski** [comment]
Will leave open for documentation reminder.

**Comment by grostim** [comment]
> Will leave open for documentation reminder.

I think you can close it now.
