### ISSUE TITLE
App request: trackarr

### ISSUE THREAD

**Issue by TheUltimateC0der** [saltyorg/Sandbox#184]
Tracker announcements to Sonarr/Radarr/Lidarr.

https://gitlab.com/cloudb0x/trackarr
https://hotio.dev/containers/trackarr/

**Comment by RaneyDazed** [comment]
Isn't this already a role? https://github.com/saltyorg/Saltbox/tree/master/roles/trackarr

**Comment by maximuskowalski** [comment]
Closing as already exists in Saltbox.

**Comment by TheUltimateC0der** [comment]
![image](https://user-images.githubusercontent.com/3315612/203882390-0bcd946e-32d3-4cba-abec-8f83510bdd5d.png)
I guess it was because I couldnt found the docs for it.
