### ISSUE TITLE
AppRequest:  fivefilters-full-text-rss

### ISSUE THREAD

**Issue by maximuskowalski** [saltyorg/Sandbox#185]
RSS feed aggregator / cleaner to use in conjunction with an RSS reader such as fresh rss.

## What's this?
An article extractor. Extract the full article content from a web page or a summary-only RSS feed. Read articles in full, in peace, in your favourite news reading application.

## News enthusiasts
Transform summary-only web feeds into full-text feeds stripped of clutter and ads. Read articles in full, in peace, in your favourite news reading application.

## Developers
Extract article content from web articles and partial feeds. Get results in XML or JSON. Use our hosted web service or download the software to run on your own servers.

https://www.fivefilters.org/full-text-rss/

https://github.com/heussd/fivefilters-full-text-rss-docker

https://github.com/heussd/fivefilters-full-text-rss-docker/blob/master/docker-compose.yml

Probably a good small role to run through with @RaneyDazed

**Comment by RaneyDazed** [comment]
Oh super! I'll take a look at it tomorrow! :D ty max!

**Comment by owine** [comment]
After a poll in Discord, this role is not planned. Feel free to submit a PR if the role is desired.
