### ISSUE TITLE
Documentation Request: tdarr

### ISSUE THREAD

**Issue by davehkb** [saltyorg/Sandbox#22]
https://github.com/HaveAGitGat/Tdarr

Tdarr is a trancoding application simmilar to unmanic, but with more plugin options.

**Comment by maximuskowalski** [comment]
Tdarr supports nvidia hardware encoding which may need to be included later, see:-
https://docs.tdarr.io/docs/installation/docker/hardware-transcoding

**Comment by saltydk** [comment]
Just follow the template for roles that use nvidia already.

**Comment by maximuskowalski** [comment]
I have already added it, what I am more meaning is I have no way to test or authenticate it as working.

**Comment by saltydk** [comment]
You need server + node bits btw.

**Comment by maximuskowalski** [comment]
Running nodes is optional I think, have included server config path but not mapped the server port. It used to be so you could run a node on another PC but its been a year since I last looked at it. Have other problems though so I will look again tomorrow, unless you can spot how I may have managed to stop any traefik stuff from being applied.

https://github.com/maximuskowalski/Sandbox/tree/feat-tdarr/roles/tdarr

I will PM you the logs.

**Comment by maximuskowalski** [comment]
Have had no reports of this role working or not so I am going to close this issue once documentation is added and assume it to be functional.

**Comment by KaHooli** [comment]
I've used Tdarr before using cloud storage, so I used to have the *arr programs move the media file to their final destination, and have Tdarr scan for file changes and transcode them there.

With cloud storage, I'd imagine you don't want the files being continually scanned and modified, and so transcoding the files after downloaded and before placed in ```/mnt/local/Media/``` would be ideal, correct?

So what would the suggested setup be for the different programs?

**Comment by maximuskowalski** [comment]
I don't really know how to use it sorry, I'd imagine a workflow that does the conversions as part of the radarr/sonarr downloading process via a copy. If you aren't planning to keep the original then I would probably try to download more suitable files to begin with. There is a tdarr discord I think, might be worth looking around there.

**Comment by KaHooli** [comment]
Hi, I think I've worked out my workflow.  But it looks like the latest version on Docker (2.0.0.13) is missing a required file.  They've just started using GHCR, and removed that version from there, I'd say due to those issues.

Can you please change the image source as per this link?: https://github.com/HaveAGitGat/Tdarr/issues/501 
So they'd be ghcr.io/haveagitgat/tdarr & ghcr.io/haveagitgat/tdarr_node instead of haveagitgat/tdarr & aveagitgat/tdarr_node

**Comment by saltydk** [comment]
Ask the docker maintainer to fix his way of removing broken images. There is no guarantee that it won't happen later with GHCR as I see it.

**Comment by maximuskowalski** [comment]
Sure, I will try to get this done in the next few hours.

**Comment by kungfoome** [comment]
Tested the current role with GHCR image. This is v2.00.18. Seems to work ok. As far as workflow goes. I update the cloudplow config to hold onto to the files for a bit.

Something like this. Depending on how much you download every day or how fast your server is, this can be adjust. Then the file will sit there locally. You can do the transcoding and then eventually it will be put up into remote storage.
```
"rclone_extras": {
  "--min-age": "1d"
  ....
}
```

**Comment by esspereira** [comment]
Does anyone know how to solve this problem in tdarr?

1-2022-08-22T10:19:01.228Z rahytaRWe:Node[MainNode]:Worker[KffQidc8o]:[Step W07] [C2] Worker [-error-]

2-2022-08-22T10:19:01.229Z rahytaRWe:Node[MainNode]:Worker[KffQidc8o]:[-error-]

3-2022-08-22T10:19:01.230Z rahytaRWe:Node[MainNode]:Worker[KffQidc8o]:Error encountered when processing /mnt/local/transcodes/tdarr/Signs (2002)-TdarrCacheFile-W47vd7To15.mkv

4-2022-08-22T10:19:01.231Z rahytaRWe:Node[MainNode]:Worker[KffQidc8o]:Checking new cache file

5-2022-08-22T10:19:01.232Z rahytaRWe:Node[MainNode]:Worker[KffQidc8o]:Tdarr ALERT: NO OUTPUT FILE PRODUCED:

6-2022-08-22T10:19:01.232Z /mnt/local/transcodes/tdarr/Signs (2002)-TdarrCacheFile-vl02hHJhXv.mkv

7-2022-08-22T10:19:01.233Z rahytaRWe:Node[MainNode]:Worker[KffQidc8o]:Updating transcode stats

**Comment by maximuskowalski** [comment]
Closing - docs request moved to docs repo see
https://github.com/saltyorg/docs/issues/113
