### ISSUE TITLE
App request: Valheim server

### ISSUE THREAD

**Issue by cubert1** [saltyorg/Sandbox#224]
[https://github.com/lloesche/valheim-server-docker](https://github.com/lloesche/valheim-server-docker)

**Comment by rrbailey89** [comment]
I second this request

**Comment by maximuskowalski** [comment]
> Valheim dedicated gameserver with automatic update, World backup, BepInEx and ValheimPlus mod support

Game server... might be a sandpit thing but will leave it here for now.

**Comment by owine** [comment]
After a poll in Discord, this role is not planned. Feel free to submit a PR if the role is desired.
