### ISSUE TITLE
App Request: Gluetun

### ISSUE THREAD

**Issue by SRBGod** [saltyorg/Sandbox#226]
Gluetun is a flexible VPN solution that allows any container to be routed through it using the container network feature in docker. Would be immensely useful for tunneling apps as needed through various VPN providers.

https://github.com/qdm12/gluetun

A simple role would allow for users to run the gluetun container and no longer need to fuss about with containers that have VPN features, instead setting up gluetun once and being able to use it for as many containers as needed.

**Comment by owine** [comment]
WIP - needs testing

https://github.com/saltyorg/Sandbox/commit/693e31ba398fc8b5aa1e492b1a1754791fda93d1
