### ISSUE TITLE
App Request: Satisfactory Server

### ISSUE THREAD

**Issue by rrbailey89** [saltyorg/Sandbox#231]
It looks like it should be pretty simple to implement, I am just to dumb to do so.

https://hub.docker.com/r/wolveix/satisfactory-server

**Comment by TechButton** [comment]
I am working on this for myself. Hopefully in a week or so I will have something

**Comment by owine** [comment]
After a poll in Discord, this role is not planned. Feel free to submit a PR if the role is desired.
