### ISSUE TITLE
PlexMetaManager: Multi-Instance Support

### ISSUE THREAD

**Issue by PuppyLover101** [saltyorg/Sandbox#238]
---

**Describe the problem**
Allow for PlexMetaManager to have [multiple app instances](https://docs.saltbox.dev/reference/multiple-instances/)

**Describe any solutions you think might work**
No traefik subdomains needed, just additional containers need to be spawned based on naming convention supplied on inventory.

**Why is this neccessary**?
Multiple docker containers are better for multiple libraries to speed up the process of each category. This is especially noticeable on larger libraries.

**Comment by chazlarson** [comment]
Running multiple PMM instances simultaneously against the same Plex instance is probably not going to improve performance significantly [since Plex is still receiving the same number of API requests, just from different sources] and may very well cause problems, so this will/would need to be festooned with caveats.

**Comment by PuppyLover101** [comment]
This also helps with config management, which is the biggest reason for my request. I have specific config files for each Library source, and I don't want one docker to run it all.

**Comment by saltydk** [comment]
Nothing prevents you from deploying multiple with the current role but having instances would need to have more upside than potential downside and outside of running multiple different Plex servers it seems without a decent use case to me.

**Comment by chazlarson** [comment]
The simplest way to manage this is going to be via `docker run` commands kicking off manual runs with different configs, or setting up the containers using `docker-compose` or the like.  You stated use case will add a bunch of complication to the sb settings, when it's just a simple to make those same settings directly.

**Comment by maximuskowalski** [comment]
> Nothing prevents you from deploying multiple with the current role but having instances would need to have more upside than potential downside and outside of running multiple different Plex servers it seems without a decent use case to me.

There are config options on a per library basis and even per plex instance or server, have run it against three very very very large libraries from the same PMM instance without issue.

**Comment by saltydk** [comment]
> > Nothing prevents you from deploying multiple with the current role but having instances would need to have more upside than potential downside and outside of running multiple different Plex servers it seems without a decent use case to me.
> 
> There are config options on a per library basis and even per plex instance or server, have run it against three very very very large libraries from the same PMM instance without issue.

Still doesn't make it a good idea.

**Comment by maximuskowalski** [comment]
I was meaning that even for different plex instances there is no need for multiple PMM instances. Config can be per library and server.

I cant see a use case for multi instance PMM.

**Comment by saltydk** [comment]
> I was meaning that even for different plex instances there is no need for multiple PMM instances. Config can be per library and server.
> 
> I cant see a use case for multi instance PMM.

Fair enough, that was not how I read that :p
