### ISSUE TITLE
App Request: immich

### ISSUE THREAD

**Issue by mtauberjr** [saltyorg/Sandbox#241]
https://github.com/immich-app/immich

**Comment by maximuskowalski** [comment]
## About
Self-hosted photo and video backup solution directly from your mobile phone.

https://immich.app/
https://github.com/immich-app/immich/blob/main/docker/docker-compose.yml
https://immich.app/docs/install/docker-compose

**Comment by ggitaceblade** [comment]
2nd this request

**Comment by GenerlAce** [comment]
here to 4th vote for an official sandbox app.  in the mean time, i was able to get a docker compose to work for immich. i am in no means smart when it comes to this stuff, but i found a reddit post which led me to this guys docker-compose which i just updated to fit saltbox network and traefik. `https://github.com/Cody-Duncan/immich_config_help`. So it may help out anyone who sees this and is looking to try.

**Comment by al13nus** [comment]
Please be aware of breaking changes: [Release v.1.88.0](https://github.com/immich-app/immich/releases/tag/v1.88.0)
