### ISSUE TITLE
App Request: Porla

### ISSUE THREAD

**Issue by PuppyLover101** [saltyorg/Sandbox#260]
https://github.com/porla/porla
https://porla.org/

A lightweight and programmable torrent client. Seems really neat from my initial tests, and the built in "PQL" language is handy.

**Comment by saltydk** [comment]
Lack of integration with arrs is the main reason I haven't added it yet.

**Comment by saltydk** [comment]
I didn't say it wasn't worth it, I said why I haven't made a role and won't until it is done. Maybe someone else will make a role before it gets arr integration but that is what I am waiting for.

**Comment by maximuskowalski** [comment]
Without arr integration I'd lean towards a Sandpit role.

**Comment by saltydk** [comment]
Closing this as it is still not whitelisted on trackers which suggests to me that it is not ready for broad usage yet.
