### ISSUE TITLE
Filebrowser Role issues

### ISSUE THREAD

**Issue by littlebirdiegr** [saltyorg/Sandbox#262]
Can someone who knows how things are done have a look at the role ? :P 

I want filebrowser to be accessible from its own domain and be protected by Cloudflare. For this to happen I edit the host and add:

> filebrowser_web_subdomain: "www"
> filebrowser_web_domain: "mydomain.com"
> filebrowser_traefik_sso_middleware: "traefik-auth"

There seems to be some issues on how it works. My main problem is that I cannot access it by just typing the main domain. I have to type www. in order to be able to access it. I would like to reach my filebrowser app just by typing mydomain.com 

An addition problem is that is not fully protected by cloudflare. Even I assign everything through cloudflare's proxy, it only protects the main domain (aka mydomain.com). If I do a reverse ip lookup with www,mydomain.com, my server's IP is exposed.

**Comment by saltydk** [comment]
As for the IP being exposed that is likely because you haven't enabled the proxy setting, if you only want to enable it for this particular app you would need to add 
```yaml
filebrowser_dns_proxy: true
```
To make it accessible on the root domain just set 
```yaml
filebrowser_web_subdomain: ""
```
