### ISSUE TITLE
App Request: Pastefy

### ISSUE THREAD

**Issue by theweasley** [saltyorg/Sandbox#272]
Requesting the addition of Pastefy as an alternate to the current pastebin app in sandbox. Pastefy has an excellent API to support it and is very user-friendly in terms of the interface for not just the end-user but also the paster.

https://github.com/interaapps/pastefy

Comes with full docker support and excellent docs for the API as well.

Thank you for the consideration.

**Comment by owine** [comment]
After a poll in Discord, this role is not planned. Feel free to submit a PR if the role is desired.
