### ISSUE TITLE
App Request: flame

### ISSUE THREAD

**Issue by Deathedit** [saltyorg/Sandbox#276]
https://github.com/pawelmalak/flame

simple and clean startpage / landingpage

![Screenshot](https://raw.githubusercontent.com/pawelmalak/flame/master/.github/home.png)

**Comment by maximuskowalski** [comment]
Might be helpful to include something about what it is or how it belongs in a saltbox setup if you are hoping to entice someone to fulfil this request.

**Comment by RaneyDazed** [comment]
I think this is really similar to homarr. #179 Just thought I'd toss in my 2 cents.

**Comment by maximuskowalski** [comment]
Cheers RD, but this is more about etiquette - I did have a look at the link, but I think expecting people to take the extra step on the off chance they might feel like helping out is not what we want to see in our app requests. Make it as easy as possible for the people you are hoping to get help from. Perhaps we need an app request template.

**Comment by keldian** [comment]
This is in Sandpit right? https://github.com/saltyorg/Sandpit/tree/main/roles/flame

Just felt I should point that out. Needs Traefik3 conversion though.

**Comment by owine** [comment]
We already have multiple homepage/landing page apps and with this in Sandpit, I'd certainly merge a PR but this is not one I am going to put work into myself.
