### ISSUE TITLE
 add xtream codes clone

### ISSUE THREAD

**Issue by daveftw84** [saltyorg/Sandbox#277]
would be neat if we can setup our own iptv server or just use vod to make a server.
i would like something that just serves media and thats it. no resume points, transcoding, tracking, etc

**Comment by maximuskowalski** [comment]
Perhaps consider including some links. I don't know what an xtream codes clone is but it sounds like you want to set up an iptv server?

I think there are existing projects for setting up iptv servers already.

**Comment by daveftw84** [comment]
https://github.com/tweakunwanted

**Comment by daveftw84** [comment]
not with docker, ez ssl, etc

**Comment by daveftw84** [comment]
or its ub 14 only https://github.com/kevcussick/xtream-codes-fixed

**Comment by daveftw84** [comment]
what a surprise...
