### ISSUE TITLE
Wordpress Login Issue with changed subdomain

### ISSUE THREAD

**Issue by jeffphilly** [saltyorg/Sandbox#28]
When attempting to enter the /login or /admin page in Wordpress, the address automatically defaults back to wordpress.domain.xyz.

At the moment it seems impossible to enter the wordpress admin portion of the site.

**Comment by saltydk** [comment]
If you setup wordpress before changing that subdomain it is probably something in Wordpress you need to edit, not something we deal with.

**Comment by jeffphilly** [comment]
Ok, let me give that a shot

**Comment by jeffphilly** [comment]
Yes, can confirm you need to make a change to the website settings prior to changing the subdomain. Thanks for the help.
