### ISSUE TITLE
Authelia and wizarr

### ISSUE THREAD

**Issue by aronjanosch** [saltyorg/Sandbox#287]
Hi,

Right now the Authelia middleware is in front of wizarr. This kind of defeats the service of wizarr, as an onboarding mechanism. Maybe it should be disabled by default or only put the authelia service in front of the admin/setup interface not the invitation link

**Comment by keldian** [comment]
Incorrect. Invitation links are endpoint whitelisted in Traefik. Close this.

**Comment by aronjanosch** [comment]
You are right, but I needed to reinstall the container for it to work. Now after reinstalling the container the invitation links are indeed whitelisted.

**Comment by saltydk** [comment]
They were always whitelisted, you just didn't follow the Traefik 3.0 migration guide.
