### ISSUE TITLE
Remove plex_autoscan or use a fork

### ISSUE THREAD

**Issue by saltydk** [saltyorg/Sandbox#292]
A per title, it is time to either remove the role or make it use one of the maintained forks out there.

**Comment by owine** [comment]
I do not use any of the forks. If someone can recommend a drop in replacement form I can migrate it, otherwise I will remove it.

**Comment by rbax82** [comment]
![image](https://github.com/saltyorg/Sandbox/assets/4734630/8048821d-c069-45cc-b983-6797da36799d)

**Comment by maximuskowalski** [comment]
I think we delete this, no responses from anyone.
