### ISSUE TITLE
App request: speedtest tracker

### ISSUE THREAD

**Issue by rbax82** [saltyorg/Sandbox#296]
Can this be added as a sandbox role please?
https://github.com/henrywhitaker3/Speedtest-Tracker

**Comment by maximuskowalski** [comment]
# Speedtest Tracker
This program runs a speedtest check every hour and graphs the results. The back-end is written in [Laravel](https://laravel.com/) and the front-end uses [React](https://reactjs.org/). It uses the [Ookla's speedtest cli](https://www.speedtest.net/apps/cli) package to get the data and uses [Chart.js](https://www.chartjs.org/) to plot the results.

A demo can be found [here](https://speedtest.henrywhitaker.com/)

## docker compose
https://github.com/henrywhitaker3/Speedtest-Tracker?tab=readme-ov-file#using-docker-compose

**Comment by owine** [comment]
Closing in favor of #354
