### ISSUE TITLE
audiobookshelf saves converted files to root instead of the admin account I created on setup

### ISSUE THREAD

**Issue by maximuskowalski** [saltyorg/Sandbox#297]
https://discord.com/channels/853755447970758686/1165039676399304758

> Thanks, I reached out to the audiobookshelf folks, and they told me that it has to be set on the --user field. I updated it in portainer with 1000:1000 and it works now, but I'm not sure how to set this with inventory. Any suggestions?

![image](https://github.com/saltyorg/Sandbox/assets/13492750/288b4685-7796-4bfd-b5ff-afbe611915fb)

**Comment by RaneyDazed** [comment]
@maximuskowalski does this just need to have the user arg added to the role? Seems that way

**Comment by saltydk** [comment]
owine already fixed it.

**Comment by RaneyDazed** [comment]
Oh ok cool
