### ISSUE TITLE
App Request Ombi with mysql DB

### ISSUE THREAD

**Issue by Linusten** [saltyorg/Sandbox#300]
It would be great if Ombi can be added as an additional app with mysql DB, since the performance is really bad with sqlite....

https://docs.ombi.app/guides/migrating-databases/

**Comment by owine** [comment]
We already have ombi available

**Comment by Linusten** [comment]
> We already have ombi available

Yes for sure, but a sqlite db is used internally. It would be great if it can be added using a mysql db. It is recommended by ombi. 
But since a migration is needed, i think it would be better to add it as an additional app like "ombi-mysql" :) 
Sadly i am not skilled enough to modify sandbox myself...

**Comment by owine** [comment]
From recollection, a simple json file in the appdata folder will tell Ombi to use a mariadb database. As the default behavior is sqlite, we should leave Sandbox as such for the default. Anyone desiring to use mariadb can do so easily with the json file and Sandbox should not handle a migration from sqlite to mariadb for obvious reasons.

I am closing this as not planned.
