### ISSUE TITLE
N8n installation faulty

### ISSUE THREAD

**Issue by Linusten** [saltyorg/Sandbox#301]
I installed n8n via sb install sandbox-n8n. The container reports an error: "    Error: EACCES: permission denied, open '/home/node/.n8n/config'
    Code: EACCES"

**Comment by saltydk** [comment]
Upstream issue they once fixed and then broke again in https://github.com/n8n-io/n8n/commit/f024d8be5a52943c0a658bfee5ec178da05f90d7 
You should report it to them instead.

**Comment by saltydk** [comment]
Original issue https://github.com/n8n-io/n8n/issues/1240
