### ISSUE TITLE
Uptime Kuma: Add functionality for multiple domain names for Status Pages

### ISSUE THREAD

**Issue by thatsnasty** [saltyorg/Sandbox#316]
Uptime kuma supports multiple domain names for status pages. [https://github.com/louislam/uptime-kuma/wiki/Status-Page#domain-names-for-status-pages](https://github.com/louislam/uptime-kuma/wiki/Status-Page#domain-names-for-status-pages)

As an example, currently i'm using uptime kuma (from a different local mediabox install not listed below) and I'm monitoring the following:

plex.feederbox.tld
plex.mediabox.tld 

and I wanted each of those to have their own public status page i.e.

status.feederbox.tld
status.mediabox.tld

Uptime kuma instructions say  `If you are using a reverse proxy, add your domain name in your reverse proxy and point to Uptime Kuma.`

Using labels in inventory could be possible (currently haven't investigated) but is it possible to add this functionality to the uptime-kuma role to be more easily configurable in inventory?

[Discord post](https://discord.com/channels/853755447970758686/1192403485057105920)

**Comment by maximuskowalski** [comment]
Any tests yet @thatsnasty ?

**Comment by saltydk** [comment]
I totally forgot about this, apologies. This can now be done through the inventory for any role:
```yaml
uptime_kuma_web_subdomain: "status"
uptime_kuma_web_host_override: "Host(`' + traefik_host + '`) || Host(`{{ 'status.myotherdomain.tld' }}`)"
```
Closing this but feel free to reopen if there is anything else.
