### ISSUE TITLE
Watchtower | Port configuration for Metrics

### ISSUE THREAD

**Issue by Barrow1990** [saltyorg/Sandbox#318]
~Requires port 8080 to be available.
Don't need this as default, Requires the option to override in Inventory 
As it stands it doesn't look for anything~

Requires a Metrics Toggle adding.
See below for API

See:
https://containrrr.dev/watchtower/arguments/#http_api_metrics

https://containrrr.dev/watchtower/metrics/

**Comment by owine** [comment]
What is the request? You can do this as a custom env via inventory

**Comment by saltydk** [comment]
This doesn't require a port mapping. Just an API router for it.

**Comment by Barrow1990** [comment]
How is this done in inventory / how do i go about putting an API router?

**Comment by saltydk** [comment]
Just add labels like Plex role does for webtools through the inventory after adding the ENV to enable the metrics, likely need to not have authelia on the endpoint.

**Comment by Barrow1990** [comment]
Thanks. Not sure what you mean.
But having looked at the plex-web-tools router settings. Seems above my understanding

**Comment by saltydk** [comment]
Just change the request into adding a metrics toggle and we'll add it whenever one of us has time.

**Comment by Barrow1990** [comment]
> Just change the request into adding a metrics toggle and we'll add it whenever one of us has time.

Sorted
