### ISSUE TITLE
Notifiarr install is broke

### ISSUE THREAD

**Issue by SolidRhino** [saltyorg/Sandbox#32]
I get the following erro when I try to install notifiarr:
`Unable to find 'notifiarr_tautulli_config' in expected paths`

Can someone please help me?

**Comment by saltydk** [comment]
I just installed it less than an hour ago. So will need more than that one line to tell what is going on with your attempt.

**Comment by saltydk** [comment]
You'll find an easier time getting help on the discord on a related note.

**Comment by SolidRhino** [comment]
Where can I find the link for the discord server?

**Comment by saltydk** [comment]
It is the chat button on shown on the repository readme.

**Comment by saltydk** [comment]
Resolved in https://github.com/saltyorg/Sandbox/commit/2111769c42d9e204454e02f46eeea32587c6a875
