### ISSUE TITLE
Stash - Open Authelia for http://stash.DOMAIN.com/graphql

### ISSUE THREAD

**Issue by ralle947** [saltyorg/Sandbox#320]
Authelia is blocking my script from accessing http://stash.domain.com/graphql

**Comment by keldian** [comment]
You're free to whitelist endpoints or remove the Authelia middleware for the app using the inventory system.

**Comment by saltydk** [comment]
I'm the one who told him to make this.

**Comment by saltydk** [comment]
@owine any chance you can look at this?

**Comment by owine** [comment]
Stash auth implementation is not in a way that we should expose anything by default as they do not protect any endpoints unless auth is turned on and an api key generated.
