### ISSUE TITLE
Issue: Some Deemix settings lost on update

### ISSUE THREAD

**Issue by YozoraXCII** [saltyorg/Sandbox#34]
When updating Deemix using the `sb install sandbox-deemix` code, a few settings are reset:

- Login credentials, meaning user has to either log in again or fetch their ARL again
- Download location, resets to `/downloads`

Is it possible for these settings to be retained?

Also, unsure about the general guidance but the Deemix URL is exposed by default as there is no 2FA for login, should Authelia be included in the default template?

**Comment by saltydk** [comment]
download folder is reset on container start, which I personally consider bad practise, so we cannot do anything about that outside of finding a new image.

https://gitlab.com/Bockiii/deemix-docker/-/blob/master/root/etc/cont-init.d/10-fix_folders#L12

As far as the login credentials we're mounting the config folder as specified by the documentation of the image and not sure what we can do about it outside of that. I suggest you take that up with the image maintainer https://gitlab.com/Bockiii/deemix-docker/-/issues

Max can probably throw Authelia on this role when he has a moment.

**Comment by kungfoome** [comment]
I'm not getting the login issue. It seems to retain my login creds after updating. I'll keep an eye out for that though. The downloads thing is super annoying. A workaround is to mount what you want to /downloads instead.

```
deemix_docker_volumes_custom:
  - /mnt/unionfs/Media/Music:/downloads
```

Authelia was added and merged already https://github.com/saltyorg/Sandbox/pull/95

**Comment by saltydk** [comment]
You should probably remove the regular download volume mounts then.

**Comment by saltydk** [comment]
```yaml
deemix_docker_volumes_global: false
```
That should do it.

**Comment by maximuskowalski** [comment]
It's been a year, is this still an issue?
