### ISSUE TITLE
App Request: Teslamate

### ISSUE THREAD

**Issue by jcrmit** [saltyorg/Sandbox#361]
# Teslamate

**What does it do? Why? Please describe.**

A powerful, self-hosted data logger for your Tesla.

## Links to further information

(https://github.com/teslamate-org/teslamate)
(https://docs.teslamate.org/docs/installation/docker)
(https://docs.teslamate.org/docs/guides/traefik)

## What are you willing to do to help?

- I will you help with making docs if this gets picked up.
- I will you help with testing.
- Happy to try to do this, but need hand holding

## Anything else you would like to add.

I am hoping there are other Telsa owners in the group 🤞

**Comment by saltydk** [comment]
Please fix the urls so they are clickable :p

**Comment by jcrmit** [comment]
Thanks @saltydk - updated

**Comment by maindust** [comment]
I picked this up today and have a working version of it but I need testers if anyone is available.

**Comment by jcrmit** [comment]
@maindust - I would be happy to help test a new app, but have not do so before and might need some assistance on how to help. If you could let me know how - noting your fork above. How can I install the Teslamate app to test and can I do in parralel from by live server?

**Comment by maximuskowalski** [comment]
Ideally you'd have forked the sandbox repo and then made a branch with your new feature.
To test you would switch your local sandbox repoorigin to the fork and then switch branches, for example:

`cd /opt/sandbox/ && git remote set-url origin https://github.com/maximuskowalski/Sandbox.git && git fetch && git pull'`

This would set it to my fork of the repo, but still on the main branch. You would then want to switch to the feature branch.

`git checkout teslaStuff` I think you can now "switch-branch" as well but not sure on exact syntax.

Then you can run the role that is being developed in that fork and branch.

**Comment by maindust** [comment]
That makes sense. What’s in my main branch is the final product that just needs testing before the MR to salty/Sandbox

**Comment by maindust** [comment]
https://github.com/saltyorg/Sandbox/pull/393
https://github.com/saltyorg/docs/pull/314

**Comment by owine** [comment]
#393 
https://github.com/saltyorg/Sandbox/commit/635edb44932a24ad9b5730f730e67ca21b7eddeb
