### ISSUE TITLE
BUG: Github Actions on Single app instead of all

### ISSUE THREAD

**Issue by Barrow1990** [saltyorg/Sandbox#378]
## Describe the bug

Not really a bug but can speed up progress.
It seems it's running the CI action on all apps within the sandbox repository.
This seems like a wasted amount of time and resources.
Would it be better to have it run when a push is done to the non main branch to just complete the workflow on the changes that have actually happened. 
Then it can run the main CI on all apps to push it to main to ensure that its passed all tests.

## To Reproduce

1. Create a fork of the main branch
2. Create a branch on the forked repo
3. Add the role / app required
4. Do a git commit on the changes
5. CI Action runs on all available roles / apps - resulting in 1+ hours of waiting for it to potentially get to your app

**Expected behavior**

1. Create a fork of the main branch
2. Create a branch on the forked repo
3. Add the role / app required
4. Do a git commit on the changes
5. CI Action runs on just the role / app you have added
6. when happy - do a pull request to main branch
7. do a CI action run on all apps before can be merged
8. create pull request to main sandbox repo
9. do ci actions required.

![image](https://github.com/user-attachments/assets/dbe694f8-43ef-4874-990d-a9cc7c43547d)

**Additional context**

Isn't per say a problem just could save time.
This has only gone up as more and more people start to contribute to the project.

**Comment by saltydk** [comment]
Because stuff can break over time we just test everything since it costs us nothing.

**Comment by saltydk** [comment]
Additionally all the roles run at the same time so speed is less of a container, outside of the main tags taking a tad longer.

**Comment by Barrow1990** [comment]
> Because stuff can break over time we just test everything since it costs us nothing.

Can totally understand this. Might as well

> Additionally all the roles run at the same time so speed is less of a container, outside of the main tags taking a tad longer.

This seems a good principle but seems to be limited to 20 runners. So whilst trying to get through 175 (at current count) and takes average 9 mins a run. You're looking at 81 mins (1 hour 21mins) for the action to complete. If you base it on always have 20 runners available.

This obviously on a perfect run.

**Comment by saltydk** [comment]
We have 1k concurrent runners on the main repo.

**Comment by saltydk** [comment]
The one doing the PR shouldn't rely on the Github actions for the test, it is more for us to rule out anything obviously broken.

**Comment by Barrow1990** [comment]
> We have 1k concurrent runners on the main repo.

Yea probably not an issue then.

**Comment by Barrow1990** [comment]
> The one doing the PR shouldn't rely on the Github actions for the test, it is more for us to rule out anything obviously broken.

Based on this I will close the bug down
