### ISSUE TITLE
Role request: ZNC

### ISSUE THREAD

**Issue by kaizensh** [saltyorg/Sandbox#4]
ZNC is an IRC network bouncer or BNC. It can detach the client from the actual IRC server, and also from selected channels. Multiple clients from different locations can connect to a single ZNC account simultaneously and therefore appear under the same nickname on IRC. Many private trackers that utilize #announce channels within their IRC network suggest using ZNC bouncer for automated torrenting.

There is a ZNC role on CB that I have previously tested which can be found here:
- https://github.com/Cloudbox/Community/blob/master/roles/znc/tasks/main.yml

Links:
- https://hub.docker.com/_/znc
- https://dangerous.tech/znc-docker-a-containerized-irc-bouncer/
- https://docs.linuxserver.io/images/docker-znc
- https://hub.docker.com/r/horjulf/docker-znc

**Comment by maximuskowalski** [comment]
I hadn't realised this had been removed. It's one I actually use. :)

I had a look yesterday at bringing roles in and I have hit a snag in trying to bring across git history for stuff like this with an existing CB role, or even the roles submitted by Sevos for adguard and mkvtoolnix - I am sure it can be done but time zones did not align for me to chat with Salty about it yet and my experimenting so far has failed.

**Comment by maximuskowalski** [comment]
Added in PR #15 
Docs still required.
