### ISSUE TITLE
Sandbox-calibre : Can't login

### ISSUE THREAD

**Issue by grostim** [saltyorg/Sandbox#42]
Hi !

I am trying to log in `https://calibre._yourdomain.com_` with my `user.name` and `user.pass` as listed in `/srv/git/saltbox/accounts.yml `.

I am getting the following error:
![Screenshot_125](https://user-images.githubusercontent.com/3714755/154064220-4af0e6e3-f38b-475b-a59e-5089de827465.jpg)

There is no additional helping message in docker logs calibre.

Am I the only one to face this issue ?

**Comment by saltydk** [comment]
The default user is abc I believe.

**Comment by grostim** [comment]
Yep. I just discovered that after reading at the details of https://github.com/linuxserver/docker-calibre
I will push a PR for saltbox docs, as this is unclear.
