### ISSUE TITLE
Transfer role PR from community to sandbox.

### ISSUE THREAD

**Issue by maximuskowalski** [saltyorg/Sandbox#49]
As per title, copy the community template for submitting a role to help and guide PRS to include information needed to assess PRs. Sandbox is looser but its also nice to have all the bits handy later when / if documentation is added.

**Comment by grostim** [comment]
I think it would be also great to have a dummy role folder to be used as a template for new role.

**Comment by maximuskowalski** [comment]
template done in basic fashion [here](https://github.com/saltyorg/Sandbox/commit/f055a33ef0bcba05f35eac0843401b96489446a0)

For a dummy role, we may need to think about how to do this outside of the actual repo or from within the docs.

**Comment by maximuskowalski** [comment]
I still think maybe an example role is a job for either documentation or a separate repo with comments. I have not had any further ideas about this.

**Comment by maximuskowalski** [comment]
I'm just going to close this. We have the template already, examples and guides are more of a Docs thing I think.
