### ISSUE TITLE
Sandbox Documentation

### ISSUE THREAD

**Issue by After-Shock** [saltyorg/Sandbox#5]
With the addition of the Sandbox Function, exiting installs will encounter the error message 
`/usr/local/bin/sb: line 302: cd: /opt/sandbox: No such file or directory`
if they have a current install before the inception of Sandbox commit#

Documentation is needed to outline what the purpose of the Sandbox function is and what installed with the users consent. 

Possibly offer the ability to only install SB Mediabox and feeder options as the later 2 generally don't need a Sandbox option.

**Comment by maximuskowalski** [comment]
Have added basics in [docs PR 13 here](https://github.com/saltyorg/docs/pull/13)

**Comment by maximuskowalski** [comment]
Mediabox apps and feederbox apps may well be within the sandbox and it is likely that new app submissions will start out here anyway.

Nothing is installed with Sandbox, you might think of it as the `dev` branch of community. All you are getting is a few text files and ability to easily install saltbox compatible apps as shared by other saltbox users. It's an ansible playbook for early access.

Currently Sandbox is a repo only and includes no apps. Technically it does have some roles but these are admin behind the scenes things needed to install other apps.

**Comment by saltydk** [comment]
@After-Shock Satisfied with the docs part?

**Comment by After-Shock** [comment]
@saltydk that'll do.
