### ISSUE TITLE
rename plex uitiLLs to plex utils

### ISSUE THREAD

**Issue by maximuskowalski** [saltyorg/Sandbox#50]
Adjust salt tilt factor when able.

**Comment by grostim** [comment]
Please note that plex-utiLLs is the correct name of the project.
https://github.com/jkirkcaldy/plex-utills

**Comment by maximuskowalski** [comment]
Yes  - Salty knows the app is named that way but feels tilted. I suggested he file the issue at their github :) - no need to actually do anything.

**Comment by grostim** [comment]
ok :)

I don't like this name either.
