### ISSUE TITLE
Role for cross-seeding automation

### ISSUE THREAD

**Issue by keldian** [saltyorg/Sandbox#54]
The obvious candidate: https://github.com/mmgoodnow/cross-seed

The goal here is to gauge interest for it as a new role. Feel free to use reactions, or comment in favor of a different project or docker image.

I may take a crack at it, or contribute if someone else does.

**Comment by RaneyDazed** [comment]
created a pull request @keldian

**Comment by maximuskowalski** [comment]
Any progress on this one?

**Comment by keldian** [comment]
Not from my end at least. AFAIK the project is still undergoing major changes pending documentation, and I wouldn't want to start something right in the middle of that, not without a full understanding of the possibilities.

**Comment by maximuskowalski** [comment]
No problem, just trying to see what issues we can clean up.

**Comment by N-sherwood** [comment]
Any progress on this role to add on our Saltbox

**Comment by RaneyDazed** [comment]
I can do that, but I think rn its a compose file. I'll have to test it, I don't believe it works w the newest qbit version. I think that's why it wasn't working for me last time I messed w it. Once I test it I can add it : )

**Comment by maximuskowalski** [comment]
Compose would be good for sandpit for now then.

**Comment by RaneyDazed** [comment]
alrighty, I'll have to make sure it hasn't been updated into oblivion since I last took a look lol

**Comment by RaneyDazed** [comment]
sandpit bound
