### ISSUE TITLE
vnstat will not start

### ISSUE THREAD

**Issue by thatsnasty** [saltyorg/Sandbox#56]
After installing, vnstat.mydomain.tld shows the following error

``` Fatal error: Uncaught Exception: JSON is invalid in /var/www/html/includes/vnstat.php:60 Stack trace: #0 /var/www/html/includes/vnstat.php(44): vnStat->processVnstatData('') #1 /var/www/html/index.php(27): vnStat->__construct('/usr/bin/vnstat') #2 {main} thrown in /var/www/html/includes/vnstat.php on line 60 ```

Docker logs
```AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.27. Set the 'ServerName' directive globally to suppress this message
[Tue Mar 22 09:49:35.441434 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.0.33 configured -- resuming normal operations
[Tue Mar 22 09:49:35.441484 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
/usr/bin/vnstat: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/bin/vnstat)
172.19.0.16 - - [22/Mar/2022:09:49:49 +1100] "GET / HTTP/1.1" 200 460 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"```

**Comment by saltydk** [comment]
Image hasn't been updated in 3 years so I'd recommend finding a replacement or removing the role.

**Comment by saltydk** [comment]
It would not, as this is the container version (web ui).

**Comment by maximuskowalski** [comment]
Going to delete this next week since we don't have any replacement image candidates.

**Comment by Cajs** [comment]
Looks like the vnstat web tool only supports vnstat 1.x and was designed around Ubuntu 14.04, with a later update for 16.04.
It looks like there was an attempt at updating support for vnstat 2.x back in 2019, but never got merged.
I'd probably consider this project abandonware at this point in time due to complete lack of commits + no response on issues / PRs.

**Comment by saltydk** [comment]
What are people using this role for? Just the network stats or more? Can do something like https://vnstat.dev.saltbox.dev/ if it is the former.

**Comment by Cajs** [comment]
Hi @saltydk ,

I personally don't use this role, but I would imagine this role is used to monitor bandwidth where customers have a data cap. For example Hetzner has a 50TB data limit if you opt for their 10Gb/s network link speed.

But this would also be useful where customers are self-hosting this on their own house, and maybe their ISP provides a data limit. In Europe this isn't common, but in America this can be very common.

Another use case is detecting issues at a later date. For example a user reports "buffering", and you spot the message 2 hours later, it's hard to diagnose, but if you spot your upload is maxing out your connection 2 hours ago (cloudplow could be doing this for example) this could explain why your seeing buffering (IOWait or overwhelming the network connection). This is especially prevalent on dedicated servers aimed at being "cheap". Quite often these provide a limited or throttled connection... OVH has Kimsufi range (max of 100mb/s) and SoYouStart range (max of 250mb/s).

Your provided example would be a great alternative. Just in case it's useful, there are other alternatives too such as collectd, netdata, prometheus/node_exporter + grafana etc etc. 

Hope this helps :)

**Comment by saltydk** [comment]
I'm well aware of the benefits of Netdata and more broad monitoring solutions but always failed to understand the web vnstat use case. Think I was mixing vnstat web with our glances role when asking the question though. The described debugging use case does not really fit into this role in my opinion as that is something Netdata or Grafana is much better suited for especially once I finally get done with the prometheus stack at some point.
