### ISSUE TITLE
Role request: Notifiarr

### ISSUE THREAD

**Issue by kaizensh** [saltyorg/Sandbox#6]
Notifiarr is a tool created to facilitate more in-depth detailed discord notifications by one of the *Arr Developers. It provides a configurable way to add notifications (including reactions) based on triggers you pick. Website provides a UI or picking what to show in the notification. Includes support for Grab, Import, Upgrade, Health, & Failed notifications in addition to much more.

I found a forked repo from the Cloudbox Mod repo that includes a custom role for Notifiarr which may provide a start
- https://github.com/media-byte/cloudbox_mod/blob/master/roles/notifiarr/tasks/main.yml

Links:
- https://github.com/Notifiarr/notifiarr
- https://hub.docker.com/r/golift/notifiarr
- https://notifiarr.wiki/

**Comment by maximuskowalski** [comment]
Merged.
