### ISSUE TITLE
App Request: Puddletag

### ISSUE THREAD

**Issue by ralleclub** [saltyorg/Sandbox#73]
**puddletag** is an audio tag editor (primarily created) for GNU/Linux similar to the Windows program, **Mp3tag**. Unlike most taggers for GNU/Linux, it uses a spreadsheet-like layout so that all the tags you want to edit by hand are visible and easily editable.

The usual tag editor features are supported like extracting tag information from filenames, renaming files based on their tags by using patterns and basic tag editing.

Then there’re Functions, which can do things like replace text, trim it, do case conversions, etc. Actions can automate repetitive tasks. Doing web lookups using Amazon (including cover art), Discogs (does cover art too!), FreeDB and MusicBrainz is also supported. There’s quite a bit more, but I’ve reached my comma quota.

Supported formats: ID3v1, ID3v2 (mp3), MP4 (mp4, m4a, etc.), VorbisComments (ogg, flac), Musepack (mpc), Monkey’s Audio (.ape) and WavPack (wv).

Links: 
- https://docs.puddletag.net/
- https://github.com/puddletag/puddletag

**Comment by owine** [comment]
Does this have a Docker container?

**Comment by maximuskowalski** [comment]
An up to date one too!
![image](https://user-images.githubusercontent.com/13492750/172094513-a9098bdf-6b19-462a-b3e2-ae59d319eaa7.png)

**Comment by maximuskowalski** [comment]
https://hub.docker.com/r/stebarraud/puddletag
and this one using guac are all I have found.
https://hub.docker.com/r/xirg/docker-puddletag
https://github.com/Xirg/docker-puddletag
