### ISSUE TITLE
App Request: PlexShare

### ISSUE THREAD

**Issue by CrashpiG** [saltyorg/Sandbox#91]
Web Application standalone that provide management of local users, many PlexServer and it's libraries.

With this web application, anyone can create an account directly this app. Every body can add his PlexServer to the list. When you are connected by default you have access to all servers. But the admin can manage permission by user or by library like limit of number streaming, the quality and other

With only one interface and without plex.tv registration, everybody can have access to the libraries of all the servers you have registered.

Features
Register and Login without plex.tv account
Manage some PlexServer to share theirs libraries
Manage permission to limit access to the users

https://github.com/Chewbaka69/PlexShare
https://chewbaka69.github.io/PlexShare

**Comment by maximuskowalski** [comment]
Docker compose example here
https://github.com/Chewbaka69/PlexShare/blob/master/docker-compose.yml
