### ISSUE TITLE
Plex Meta Manager: Missing default value

### ISSUE THREAD

**Issue by nickstarkloff** [saltyorg/Sandbox#97]
Missing default value for `plex_meta_manager_web_port`. This causes the installation to fail.

https://github.com/saltyorg/Sandbox/blob/61412e0b29eed4eefb54b72afd058d0bbb8f9371/roles/plex_meta_manager/defaults/main.yml#L37-L44

But even if you set this variable it is not being used and could be removed, right?

**Comment by maximuskowalski** [comment]
There is no web interface for it so it is not needed or used. Do you have the log capturing the failure message? I have installed this recently on someones server and it did not fail so must be related to recent changes.

**Comment by nickstarkloff** [comment]
I don't have the exact message right now but it was something like "invalid port" during the container creation.

But I just checked the recent changes and I think it already got fixed yesterday.
https://github.com/saltyorg/Saltbox/commit/c76770decce640f0b0713bbcb74cf03ea7ce63f1

I will try it again in a moment.

**Comment by maximuskowalski** [comment]
Thanks. it looks like you are correct.

**Comment by nickstarkloff** [comment]
Just to confirm .. there is no error with the latest version. Thanks! 🙂

**Comment by saltydk** [comment]
Yeah, that was my bad. Running a filter on something that could get omitted...
